#! /bin/zsh -f

# ACM: The AWS Context Manager - Changes up your account IDs and credentials for your command line tools when switching AWS accounts.


# Process commands:
function printUsage {
cat<<EOF
acm: Sets, creates and deletes AWS contexts.

Usage: acm <command> 

Command is one of the following:
<none> - Prints the context you are currently in 
create <context> - creates a new context
switch <context> - switches to a context
delete <context> - deletes a context
disable - Touches a file to disable ACM
verbose - Prints your context before running any EC2 commands

See http://github.com/

EOF
}
# Startup:
# Check for ~/.acm directory, create it if neccessary
if [[ ! -d ~/.acm ]]; then
    mkdir -p ~/.acm/contexts
    if [[ $? -ne 0 ]]; then
	echo Could not create ~/.acm/contexts. Exiting...
	exit 1
    fi
fi

case "$1" in
    disable)
	touch ~/.acm/disabled
	echo Disabling AWS context Manager
	;;
    enable)
	rm ~/.acm/disabled
	echo Enabling AWS context Manager
	;;
    verbose)
	touch ~/.acm/verbose
	echo Making AWS context Manager be verbose
	;;
    quiet)
	rm ~/.acm/verbose
	echo Making AWS context Manager quiet
	;;
    create)
	if [[ -e ~/.acm/contexts/$2 ]]; then
	    echo Context ~/.acm/contexts/$2 appears to already exist.
	    echo You must delete this file to create a new context with the same name, or edit it directly to change it.
	else
	    cat > ~/.acm/contexts/$2 <<EOF
# AWS context $2
export EC2_PRIVATE_KEY=
export EC2_PRIVATE_KEY=
export EC2_CERT=
export AWS_USER_ID=
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
EOF
	    echo Context skeleton created. You must edit ~/.acm/contexts/$2 to add the proper values for your context.
	fi
	;;
    switch)
	if [[ -e ~/.acm/contexts/$2 ]]; then
	    ln -sf ~/.acm/contexts/$2 ~/.acm/configured_context
	    if [[ $? -ne 0 ]]; then
		echo Error creating link to ~/.acm/contexts/$2
	    fi
	else
	    echo Context $2 does not seem to exist.
	fi
	;;
    delete)
	if [[ -e ~/.acm/contexts/$2 ]]; then
	    rm ~/.acm/contexts/$2
	    if [[ $? -ne 0 ]]; then
		echo Error removing ~/.acm/contexts/$2
	    fi
	else
	    echo Context $2 does not seem to exist.
	fi
	;;
    list)
	echo AWS contexts:
	ls -1 ~/.acm/contexts
	;;
    '')
	if [[ -h ~/.acm/current_context ]]; then
	    echo AWS context is `readlink ~/.acm/configured_context`
	else
	    echo No AWS context selected
	fi
	;;
    *)
	printUsage
	;;
	
esac